name: DonkeyBorder
version: '${project.version}'
main: me.olios.plugins.donkeyborder.DonkeyBorder
api-version: 1.20
commands:
  setborder:
    aliases:
      - setb
      - sb
    usage: /<command>
    description: set the border
