name: DonkeyBorder
version: '${project.version}'
main: me.olios.plugins.donkeyborder.DonkeyBorder
api-version: 1.20
commands:
  setborder:
    aliases:
      - setb
      - sb
    usage: /<command>
    description: set the border and summoned the Donkey

    tpdonkey:
      aliases:
        - tpd
      usage: /<command>
      description: teleport the player to the Donkey location
